### ISSUE TITLE
bug SocialiteManager

### ISSUE THREAD

**Issue by zzyycoder** [xjchengo/component-wechat#1]
add
public function getRequest()
{
    return $this->request;
}
to SocialiteManager.php

**Comment by zzyycoder** [comment]
你好，我怎么联系你。在使用你的项目，有些问题想请教。wo_1988818@163.com，这是我的个人邮箱。

**Comment by xjchengo** [comment]
有什么可以帮你的吗？

**Comment by zzyycoder** [comment]
非常感谢你的回复，前段时间用了你的这个项目，刚开始有些疑问，不过现在都解决了，谢谢！
